### ISSUE TITLE
console runner: changeFile

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw-forge/tutorial-compiler#22]
Implement the command changeFile in the console runner. Gets the path of a file, the name of a placeholder and a string that should be inserted or the path of a file with the content that should inserted. Maybe you need to use named parameters.

**Comment by GuentherJulian** [comment]
The second paramter is implemented as JSON object. It contains the placeholder and the content respectively the path to the file the content is get from. The placeholder parameter is optional. If no placeholder is given, all content is replaced.
