### ISSUE TITLE
console runner: installDevonIde

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw-forge/tutorial-compiler#3]
Implement the command installDevonIde in the console runner. The command gets the modules to install as parameter. To implement the command a bare git repo could be the way to go.
Get the version from the variable ide.version if it is set. Otherwise use the last released version.

**Comment by GuentherJulian16** [comment]
In this task only the installation of the latest released version is implemented.
The possibility to configure the version will be realized in another task (https://github.com/devonfw-forge/tutorial-compiler/issues/23)

**Comment by GuentherJulian** [comment]
In this task only the installation of the latest released version of the devonfw ide is implemented.
The possibility to configure the version which will be installed is realized in another task (https://github.com/devonfw-forge/tutorial-compiler/issues/24)
