### ISSUE TITLE
console runner: restoreDevonfwIde

### ISSUE THREAD

**Issue by GuentherJulian** [devonfw-forge/tutorial-compiler#56]
Implement the command restoreDevonfwIde in the console runner. Gets the modules to install as parameter.
The command does the same as the command installDevonfwIde.

**Comment by TheMarcy** [comment]
If this command does the same as installDevonfwIde why is it needed? Wouldn't it be better if it skips the cloning of the repo and  the download of the file needed for setup, because an installation before already did that?

**Comment by maybeec** [comment]
I agree, @GuentherJulian could you scetch the difference? Possibly it's just a different parameterization?
In any case @TheMarcy, depending on what @GuentherJulian had in mind here, it might be easier to create a new api which internally reuses the devonfw ide step

**Comment by GuentherJulian** [comment]
The idea behind this command is to have an installed devon ide the user can use without installing it manually in an own step. This is only relevant for the katacoda tutorials. There this is realized by an startup script which installs the ide before the first step starts.
In the console runner we do not need this. There we just need an working ide. However to work with the all tutorials this command has to be implemented in the console runner.
